# -*- coding: utf-8 -*-
"""face_detection_mediapipe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xrgl1-weAt9O_A6jq_lhcYW-N2y4xh-l

**Install and Import Libraries**
"""

!pip install mediapipe

import cv2
import math
import numpy as np
from google.colab.patches import cv2_imshow

from google.colab import files
upload=files.upload()
short_range_images={name : cv2.imread(name) for name in upload.keys()}

import mediapipe as mp

mp_face_detection=mp.solutions.face_detection

#get drwaing utilities for draw boundaries
mp_drawing=mp.solutions.drawing_utils
drwaing_spec=mp_drawing.DrawingSpec(thickness=1, circle_radius=1)

with mp_face_detection.FaceDetection(min_detection_confidence=0.5, model_selection=0) as face_detection: # 0 for short range images
  for name,image in short_range_images.items():
    result=face_detection.process(cv2.cvtColor(image,cv2.COLOR_BGR2RGB))  #open cv deal with only gray images but mediapipe want them in RGB mode

    # Exception handling
    if not result.detections:
      continue

    for detection in result.detections:
      mp_drawing.draw_detection(image,detection)
    cv2_imshow(image)